seata:
  enabled: true
  application-id: business-service
  tx-service-group: my_test_tx_group
  #使用mybatis-plus必须手动配置数据源
  enable-auto-data-source-proxy: false
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace:
      group: SEATA_GROUP
  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: 127.0.0.1:8848
      group: SEATA_GROUP